version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  migrations:
    image: python:3.11-slim
    container_name: db_migrations
    depends_on:
      - db
    working_dir: /fastapi_app
    volumes:
      - .:/fastapi_app
    entrypoint: ["sh", "-c", "python src/init_db.py"]  # Запуск миграций
    environment:
      DATABASE_URL: "postgresql+asyncpg://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    depends_on:
      - db
      - migrations
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql+asyncpg://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}"
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  postgres_data:
